// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://melciqhlbborvlxwamkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbGNpcWhsYmJvcnZseHdhbWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjA0NzYsImV4cCI6MjA2MDczNjQ3Nn0.GSAZHqwXzcq2lP--cQJPGEdVQh20RNEZY3JnP61o7is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);